import {initState} from './store';

const universityStore = () =>
{

  const setData = ({type, data}, globalState) => ({[type]: data});

  const initialState = (payload, globalState) => ({
    administrativestaffs: [],
    accreditations: [],
    accrs: [],
    annualprofessionaldevelopmentplans: [],
    aaims: [],
    pdc_aims: [],
    aannualprograms: [],
    achievements: [],
    academiccalendars: [],
    acapacitybuildings: [],
    achievements: [],
    acouncilscommittees: [],
    aggrements: [],
    amanualpolicies: [],
    selfassesments: [],
    periodicprogramreviews: [],
    avissionmissionimages: [],
    boardinfos: [],
    boardmembers: [],
    boardposts: [],
    capacitybuildings: [],
    ccurriculums: [],
    curriculums: [],
    ceabouts: [],
    ceaggrements: [],
    cemissions: [],
    ceorganizationalstructures: [],
    cevissions: [],
    chancellormessages: [],
    contactinfos: [],
    contactus: [],
    eligibilitycriterias: [],
    faculties: [],
    heros: [],
    histories: [],
    jobs: [],
    libraries: [],
    libraryinfos: [],
    labs: [],
    magazines: [],
    migrationpolicies: [],
    news: [],
    foundation: [],
    orgstructures: [],
    pdcstructures: [],
    pdcposts: [],
    policiesandprocedures: [],
    pdcstaticks: [],
    penalties: [],
    raims: [],
    researchpublications: [],
    researchpapersandpublications: [],
    researchsupports: [],
    researchpapers: [],
    researchguides: [],
    researchtrainings: [],
    rmanualpolicies: [],    
    planedresearches: [],
    underprocessresearches: [],
    completedresearches: [],
    publishedresearches: [],
    scholarshipsfinancings: [],
    semesterpromotionrules: [],
    stratigicaims: [],
    seminarscoursesworkshops: [],
    scientificandresearchmagazines: [],
    teachers: [],
    pdcstudents: [],
    societies: [],
    students: [],
    values: [],
    strategicplanes: [],
    structures: [],
    semesterfees: [],
    councilsandcommittees: [],
    academicprograms: [],
    });
  
  return initState({
    initialState, 
    setData, 
  })
}


export default universityStore;