import LocalizedStrings from 'react-localization';

let languages = new LocalizedStrings({
  en:{
    home: "Home",
    contact: "Contact",
    about: "About",
      our_vission_and_mission: "Our Vission and Mission",
      chancellor_message: "Chancellor's Message",
      history_and_achievements: "History & Achievements",
      organizational_structure: "ORG Structure",
      stratigic_aim: "Stratigic Aim",
      academic_calendar: "Academic Calendar",
      aggrements: "Aggrements",
      
    a_pdc: "Professional Development Center",
      a_pdc_b: "Professional Development Board",
    
      
    academics: "Academics",
      a_quality_assurance: "Quality Assurance",
        a_aims: "Aims",
        a_self_assesment: "Self Assesment",
        a_annual_program_monitoring: "Annual Program Monitoring",
        a_councils_committees: "Councils & Committees",
        a_manual_policies: "Manual & Policies",
        a_capacity_building: "Capacity Building",
        accreditation: "Accreditation",
      a_bcs_computer_science: "BCS Computer Science",
      a_bba_economics: "BBA Economics",
        a_vission_mission: "Vission, Mission & About",
        a_curriculum: "Curriculum",
        a_organizational_structure: "Organizational Structure",
        a_aggrements: "Aggrements",

    research: "Research",
      capacity_building: "Capacity Building", 
      r_vission_mission: "Vission & Mission",
      manual_policies: "Manual & Policies",
      saba_magazine: "Saba Magazine",
      research_publications: "Research Publications",

    students: "Students",
      student_portal: "Student Portal",
      eligibility_criteria: "Eligibility Criteria",
      scholarships_financing: "Scholarships & Financing",
      migration_policy: "Migration Policy",
      semester_promotion_rules: "Semester Promotion Rules",
      students_verification: "Students Verification",
      penalties: "Penalties",


    online_library: "Online Library",
    news: "News",
    job_opportunity: "Job Opportunity",
    kankor: "Kankor",
      online_admission: "Online Admission",
      result: "Result",
    economical_advisory: "S E A Board",
    nothing_to_show: "Nothing To Show Yet",
    no_posts: "No Posts To Show",
    posts: "Posts",
    chancellor_of_saba: "chancellor of saba university",
    history_of_saba: "History Of Saba University",
    achievements: "Achievements",
    annual_two_semesters: "Annual two semesters",
    a_about: "About",
    author: "Author",
    page: "Page",
    related: "Related",
    document: "Document",
    fullName: "Full Name",
    fatherName: "Father Name",
    faculty: "Faculty",
    id: "ID",
    yourDocuments: "Your Documents",
    sabaStudentsPortal: "Saba University Students Portal",
    logOut: "LogOut",
    graduated_date: "Graduated Date",
    menu: "MENU",
    saba_foundation: "Saba Foundation",
    vission: "Vission",
    mission: "Mission",
    structure: "Structure",
    values: "Values",
    years_plane: "Five-Years Stratigic Plan",
    strategic_plane: "Strategic Plan",
    downloadPlanFile: "Download Plan File",
    councils_and_committees: "Councils And Committees",
    academic_programs: "Academic Programs",
    your_opinion: "Your Opinion",
    write_opinion: "Write Your Opinion To Us",
  },
  ps:{
    home: "کور",
    // About
    about: "زموږ په اړه",
      our_vission_and_mission:"لرلید او رسالت",
      chancellor_message: "د رئیس پیغام",
      history_and_achievements: "لاسته راوړنې",
      organizational_structure: "اداري جوړښت",
      stratigic_aim: "ستراتیژیکې موخې",
      academic_calendar: "علمي تقویم",
      aggrements: "هوکړه لیکونه",

    a_pdc: "مسلکي پرمختیایي مرکز",
      a_pdc_b: "مسلکي پرمختیایی پورډ",
    // Academic
    academics: "علمي پروګرامونه",
      a_quality_assurance: "تضمین کیفیت",
        a_aims: "اهداف",
        a_self_assesment: "ځان ارزونې اصلي او فرعي معیارونه",
        a_annual_program_monitoring: "کلنی څارنه",
        a_councils_committees: "کمېټې او شوراګانې",
        a_manual_policies: "پالیسیانې او طرزالعملونه",
        a_capacity_building: "ورکشاپونه او سمیینارونه",
        accreditation: "اعتبار اخیستنه",
      a_bcs_computer_science: "کمپیوټرساینس",
      a_bba_economics: "اقتصاد",
        a_vission_mission: "لرلید رسالت او موخې",
        a_curriculum: "نصاب",
        a_organizational_structure: "اداري جوړښت",
        a_aggrements: "هوکړه لیکونه",


    // Rechearch
    research: "څیړنیز مرکز",
      capacity_building: "ورکشاپونه او سمیینارونه", 
      r_vission_mission: "لرلید، رسالت او موخې",
      manual_policies: "پالیسیانې او طرزالعملونه",
      saba_magazine: "سبا څېړنیزه مجله",
      research_publications: "نشر سوې څېړنې",
      
    // Students
    students: "محصلان",
      student_portal: "د محصل معلومات",
      eligibility_criteria: "د داخلې شرائط",
      scholarships_financing: "د محصلانو مالي تمویل او تشویق",
      migration_policy: "تبدیلي",
      semester_promotion_rules: "د سمیستر ناکامي",
      students_verification: "د فراغت اسنادو تصدیق",
      penalties: "د ډسپلین خلاف کړنې او مجازات",


    online_library: "سبا کتابتون",
    news: "خبرونه",
    contact: "اړیکه",
    job_opportunity: "کاري فرصت",

    // Kankor
    kankor: "کانکور",
      online_admission: "آنلاین نوملیکنه",
      result: "نتیجه",

    economical_advisory: "اقتصادی مشورتی بورډ",
    nothing_to_show: "تر اوسه د ښودلو لپاره هیڅ شی نشته",
    no_posts: "No Posts To Show",
    posts: "پوسټونه",
    chancellor_of_saba: "د سبا پوهنتون رییس",
    history_of_saba: "د سبا پوهنتون تاریخ",
    achievements: "لاسته راوړنې",
    annual_two_semesters: "کلني دوه سمسترونه",
    author: "لیکوال",
    page: "ګڼه",
    a_about: "موخی",
    related: "اړوند",
    document: "سند",
    fullName: "بشپړ نوم",
    fatherName: "د پلار نوم",
    faculty: "پوهنځی",
    id: "آیډی",
    yourDocuments: "ستاسو اسناد",
    sabaStudentsPortal: "د سبا پوهنتون محصلینو پورټل",
    logOut: "وتل",
    graduated_date: "د فراغت نیټه",
    menu: "مینیو",
    saba_foundation: "سبا مرستندویه بنیاد",
    structure: "Structure",
    vission: "Vission",
    mission: "Mission",
    values: "ارزښتونه",
    years_plane: "پنځه کلن ستراتیژیک پلان",
    strategic_plane: "ستراتیژیک پلان",
    downloadPlanFile: "د پلان فایل ډاونلوډ کړی",
    councils_and_committees: "شوراګانی او کمیټی",
    academic_programs: "علمی برنامی",
    your_opinion: "ستاسو نظر",
    write_opinion: "موږ ته دی نظر ولیکه",
  }
});



export default languages;