import LocalizedStrings from 'react-localization';

let languages = new LocalizedStrings({
  en:{
    textDirection: "ltr",
    home: "Home",
    contact: "Contact",
    about: "About Us",
      vission_mission: "Vission & Mission",
      our_vission_and_mission: "Vission & Mission",
      chancellor_message: "Chancellor's Message",
      history_and_achievements: "History & Achievements",
      organizational_structure: "ORG Structure",
      stratigic_aim: "Stratigic Aim",
      academic_calendar: "Academic Calendar",
      aggrements: "Aggrements",
      
    a_pdc: "Professional Development",
      a_pdc_b: "Professional Development Board",
    
      
    academics_programs: "Academics Programs",
      academics: "Academics",
      a_quality_assurance: "Quality Assurance",
        a_aims: "Aims",
        a_self_assesment: "Self Assesment",
        a_annual_program_monitoring: "Annual Program Monitoring",
        a_councils_committees: "Councils & Committees",
        a_manual_policies: "Manual & Policies",
        a_capacity_building: "Capacity Building",
        accreditation: "Accreditation",
      a_bcs_computer_science: "Computer Science",
      a_bba_economics: "Economics",
        a_vission_mission: "Vission, Mission & About",
        a_curriculum: "Curriculum",
        a_organizational_structure: "Organizational Structure",
        a_aggrements: "Aggrements",

    research: "Research",
      quality: "Quality",
      research_quality: "Research & quality",
      capacity_building: "Capacity Building", 
      r_vission_mission: "Vission & Mission",
      manual_policies: "Manual & Policies",
      saba_magazine: "Saba Magazine",
      research_publications: "Research Publications",

    student: "Students",
      student_portal: "Student Portal",
      eligibility_criteria: "Eligibility Criteria",
      scholarships_financing: "Scholarships & Financing",
      migration_policy: "Migration Policy",
      semester_promotion_rules: "Semester Promotion Rules",
      students_verification: "Students Verification",
      penalties: "Penalties",


    saba_library: "Saba Library",
    news: "News",
    job_opportunity: "Job Opportunity",
    kankor: "Kankor",
      online_admission: "Online Admission",
      result: "Result",
    saba_economical_board: "Saba Economical Board",
    nothing_to_show: "Nothing To Show Yet",
    no_posts: "No Posts To Show",
    posts: "Posts",
    chancellor_of_saba: "chancellor of saba university",
    history_of_saba: "History Of Saba University",
    achievements: "Achievements",
    annual_two_semesters: "Annual two semesters",
    a_about: "About",
    author: "Author",
    page: "Page",
    related: "Related",
    document: "Document",
    fullName: "Full Name",
    fatherName: "Father Name",
    faculty: "Faculty",
    faculties: "Faculties",
    id: "ID",
    yourDocuments: "Your Documents",
    sabaStudentsPortal: "Saba University Students Portal",
    logOut: "LogOut",
    graduated_date: "Alumni Date",
    menu: "MENU",
    saba_foundation: "Saba Foundation",
    vission: "Vission",
    mission: "Mission",
    structure: "Structure",
    values: "Values",
    years_plane: "Five-Years Stratigic Plan",
    strategic_plane: "Strategic Plan",
    strategic_aims: "Strategic Aims",
    downloadPlanFile: "Download File",
    councils_and_committees: "Councils & Committees",
    academic_programs: "Academic Programs",
    your_opinion: "Your Opinion",
    write_opinion: "Write Your Opinion To Us",
    academic_calendar : "Academic Calendar",
    informational_technology: "Informational Technology",
    curriculum: "Curriculum",
    labs: "Labs",
    library: "Library",
    libraryinfos: "Library Information",
    semester_fee: "Semester Fee",
    software_engineering: "Software Engineering",
    information_system: "Information System",
    national_economics: "National Economics",
    banking: "Banking",
    business_administration: "Business & Administration",
    research_support: "Research Support",
    research_trainings: "Research Trainings",
    policies_and_procedures : "Policies & Procedures",
    research_papers_and_publications: "Research Papers & Publications",
    scientific_and_research_magazine: "Scientific & Research Magazine",
    research_paper: "Research Papers",
    research_guide: "Research Guide",
    research_activities: "Research Activities",
    planed_researche : "Planed Researches",
    under_process_researche: "Under Process Researches",
    completed_researche: "Completed Researches",
    published_researche: "Published Researches",
    annual_professional_development_plan: "Annual Professional Development Plan",
    seminars_courses_workshop: "Seminars Courses Workshops",
    teacher: "Teachers",
    administrative_staff: "Administrative Staffs",
    society: "Society",
    periodic_program_review: "Periodic Program Review",
    internal_accreditation: "Internal Accreditation",
    national_accreditation: "National Accreditation",
    international_accreditation: "International Accreditation",
    offline_enrollment_requirement: "Offline Enrollment Requirements",
    kankor_guide: "Kankor Guide", 
    kankor_registration_date : "Kankor Registration Date", 
    enrolled : "Enrolled", 
    general: "General",
    activity: "Activities",
    online_library : "Online Library",
    digital_library: "Digital Library",
    offline_library : "Offline Library",
    procedure: "Procedure",
    study_statistic: "Study Statistics",
    progressive_plan:"Progressive Plan",
    students_engagement:"Students Engagements",
    students_experience: "Students Experiences",
    tours_of_student: "Academic Tours of Students",
    students_statistic: "Students Statistics",
    tajil : "Tajil",
    deprived: "Deprived",
    chance: "Chance",
    re_enrollment: "Re-Enrollment",
    eresticate: "Eresticate",
    transformation: "Transformation",
    repeat: "Repeat",
    graduate: "Alumni",
    cs_graduate: "CS Alumni",
    eco_graduate: "ECO Alumni",
    graduated_students_statistic: "Alumni Statistics",
    employed_student: "Employed Students",
    counseling_center: "Counseling Center",
    pdc_student: "Students",
    cs: "Computer Science",
    eco: "Economy",
    email: "Email",
    phone: "Phone",
    job: "Job",
    startDate: "Start Date",
    endDate: "End Date",
    searchById: "Search by ID",
    board: "Board",
    more: "More",
    student_services: "Student Services",
    policies_counsel: "Policies, Counsel",
    resourses: "Resourses",
    support_services: "Support Services",
    enrollment_information: "Enrollment Information",
    guidance_general: "Guidance & General Info",
    guidelines: "Guidelines",
    institutions: "Institutions",
    find_out_more: "Find Out More",
    it_information: "IT Network refers to the design, implementation, and management of computer networks for data communication. It includes networking hardware, protocols, security, and troubleshooting to ensure efficient and secure connectivity.",
    se_information: "Software Engineering is the process of designing, developing, testing, and maintaining software applications using engineering principles. It focuses on creating reliable, scalable, and efficient software solutions to meet user and business needs.",
    is_information: "Information Systems focus on the collection, processing, storage, and distribution of information using technology. It integrates software, hardware, and data management to support decision-making and business operations efficiently.",
    neco_economics: "Studies the overall economic structure of a country, including production, consumption, trade, and government policies. It focuses on economic growth, inflation, employment, and fiscal management to ensure national stability and development.",
    beco_economics: "involves the management of financial transactions, including deposits, loans, investments, and payment processing. It plays a crucial role in economic growth by providing financial services to individuals, businesses, and governments.",
    baeco_economics: "involves planning, organizing, and managing business operations to achieve efficiency and growth. It covers areas such as finance, marketing, human resources, and strategic decision-making to ensure business success.",

  },
  ps:{
    textDirection: "rtl",
    home: "کور",
    // About
    about: "زموږ په اړه",
      vission_mission:"لرلید او رسالت",
      chancellor_message: "د رئیس پیغام",
      history_and_achievements: "لاسته راوړنې",
      organizational_structure: "اداري جوړښت",
      stratigic_aim: "ستراتیژیکې موخې",
      academic_calendar: "علمي تقویم",
      aggrements: "هوکړه لیکونه",

    a_pdc: "مسلکي پرمختیایي مرکز",
      a_pdc_b: "مسلکي پرمختیایی بورډ",
    // Academic
    academics_programs: "علمي پروګرامونه",
      academics: "علمي",
      a_quality_assurance: "تضمین کیفیت",
        a_aims: "اهداف",
        a_self_assesment: "ځان ارزونې اصلي او فرعي معیارونه",
        a_annual_program_monitoring: "کلنی څارنه",
        a_councils_committees: "کمېټې او شوراګانې",
        a_manual_policies: "پالیسیانې او طرزالعملونه",
        a_capacity_building: "ورکشاپونه او سمیینارونه",
        accreditation: "اعتبار اخیستنه",
      a_bcs_computer_science: "کمپیوټرساینس",
      a_bba_economics: "اقتصاد",
        a_vission_mission: "لرلید رسالت او موخې",
        a_curriculum: "نصاب",
        a_organizational_structure: "اداري جوړښت",
        a_aggrements: "هوکړه لیکونه",


    // Rechearch
    research: "څیړنی",
    research_quality: "Research & quality",
    quality: "Quality",
      capacity_building: "ورکشاپونه او سمیینارونه", 
      r_vission_mission: "لرلید، رسالت او موخې",
      manual_policies: "پالیسیانې او طرزالعملونه",
      saba_magazine: "سبا څېړنیزه مجله",
      research_publications: "نشر سوې څېړنې",
      
    // Students
    pdc_student: "محصلان",
    student: "محصلان",
      student_portal: "د محصل معلومات",
      eligibility_criteria: "د داخلې شرائط",
      scholarships_financing: "د محصلانو مالي تمویل او تشویق",
      migration_policy: "تبدیلي",
      semester_promotion_rules: "د سمیستر ناکامي",
      students_verification: "د فراغت اسنادو تصدیق",
      penalties: "د ډسپلین خلاف کړنې او مجازات",


    saba_library: "سبا کتابتون",
    news: "خبرونه",
    contact: "اړیکه",
    job_opportunity: "کاري فرصت",

    // Kankor
    kankor: "کانکور",
      online_admission: "آنلاین نوملیکنه",
      result: "نتیجه",

    saba_economical_board: "سبا اقتصادي بورډ",
    nothing_to_show: "تر اوسه د ښودلو لپاره هیڅ شی نشته",
    no_posts: "No Posts To Show",
    posts: "پوسټونه",
    chancellor_of_saba: "د سبا پوهنتون رییس",
    history_of_saba: "د سبا پوهنتون تاریخ",
    achievements: "لاسته راوړنې",
    annual_two_semesters: "کلني دوه سمسترونه",
    author: "لیکوال",
    page: "ګڼه",
    a_about: "موخی",
    related: "اړوند",
    document: "سند",
    fullName: "بشپړ نوم",
    fatherName: "د پلار نوم",
    faculty: "پوهنځی",
    faculties: "پوهنځی",
    id: "آیډی",
    yourDocuments: "ستاسو اسناد",
    sabaStudentsPortal: "د سبا پوهنتون محصلینو پورټل",
    logOut: "وتل",
    graduated_date: "د فراغت نیټه",
    menu: "مینیو",
    saba_foundation: "سبا مرستندویه بنیاد",
    structure: "جوړښت",
    vission: "لرلید",
    mission: "رسالت",
    values: "ارزښتونه",
    years_plane: "پنځه کلن ستراتیژیک پلان",
    strategic_plane: "ستراتیژیک پلان",
    strategic_aims: "ستراتیژیکی موخی",
    downloadPlanFile: "فایل ډاونلوډ کړی",
    councils_and_committees: "شوراګانی او کمیټی",
    academic_programs: "علمی برنامی",
    your_opinion: "ستاسو نظر",
    write_opinion: "موږ ته دی نظر ولیکه",
    academic_calendar : "علمي تقویم",
    informational_technology: "معلوماتي ټکنالوژي",
    curriculum: "نصاب",
    labs: "لیبونه",
    library: "کتابتون",
    libraryinfos: "د کتابتون معلومات",
    semester_fee: "سمسټر فیس",
    software_engineering: "سافټویر انجینري",
    information_system: "معلوماتي سیسټمونه",
    national_economics: "ملی اقتصاد",
    banking: "بانکداري",
    business_administration: "اداره او تجارت",
    research_trainings: "څیړنیزه روزنه",
    research_support: "څیړنیز ملاتړ",
    policies_and_procedures : "پالیسیاني او طرزالعملونه",
    research_papers_and_publications: "څیړنیز اثار او انتشارات",
    scientific_and_research_magazine: "علمي او څیړنیزه مجله",
    research_paper: "څیړنیزي مقالي",
    research_guide: "د څیړني لارښود",
    research_activities: "څیړنیزي کړني",
    planed_researche : "پلان سوي څیړني",
    under_process_researche: "تر کار لاندي څیړني",
    completed_researche: "تکمیل سوي څیړني",
    published_researche: "نشر سوي څیړني",
    annual_professional_development_plan: "کلنی مسلکي پرمختیایی پلان",
    seminars_courses_workshop: "سیمینارونه ورکشاپونه کورسونه ",
    teacher: "استادان",
    administrative_staff: "اداري او خدماتی کارمندان",
    society: "ټولنه",
    periodic_program_review: "دورئی بیاکتنه",
    internal_accreditation: "داخلی اعتبار اخیستنه",
    national_accreditation: "ملي اعتبار اخیستنه",
    international_accreditation: "بین المللی اعتبار اخیستنه",
    offline_enrollment_requirement: "د حضوري نوم لیکني شرایط",
    kankor_guide: "د کانکور لارښود", 
    kankor_registration_date : "د کانکور د نوم لیکني نیټه", 
    enrolled : "اختصاصي", 
    general: "عمومي",
    activity: "فعالیتونه",
    online_library : "انلاین کتابتون",
    digital_library: "ډیجیټل کتابتونه",
    offline_library : "حضوري کتابتونه",
    procedure: "طرزالعمل",
    study_statistic: "مطالعه کوونکو احصائیه",
    progressive_plan:"انکشافي پلان",
    students_engagement:"د محصلانو بوختیا",
    students_experience: "د محصلانو تجارب",
    tours_of_student: "د محصلانو علمي سیرونه",
    students_statistic: "د محصلانو احصائیه",
    tajil : "تاجیل",
    deprived: "محروم",
    chance: "چانس",
    re_enrollment: "بیاشمولیت",
    eresticate: "منفک",
    transformation: "تبدیلی",
    repeat: "ریپیټ",
    graduate: "فارغان",
    cs_graduate: "فارغان",
    eco_graduate: "فارغان",
    graduated_students_statistic: "دفارغ  محصلانو احصائیه",
    employed_student: "پرکار ګمارل سوي",
    counseling_center: "مشورتي مرکز",
    cs: "کمپیوټرساینس",
    eco: "اقتصاد",
    email: "ایمیل",
    phone: "شمیره",
    job: "دنده",
    startDate: "شروع نیټه",
    endDate: "ختم نیټه",
    searchById: "Search by ID",
    board: "بورډ",
    more: "نور",
    student_services: "زده کوونکو خدمتونه",
    policies_counsel: "Policies, Counsel",
    resourses: "Resourses",
    support_services: "Support Services",
    enrollment_information: "Enrollment Information",
    guidance_general: "Guidance & General Info",
    guidelines: "Guidelines",
    institutions: "Institutions",
    find_out_more: "نور معلومات ترلاسه کړئ",
    it_information: "د معلوماتي ټکنالوژۍ شبکه د کمپیوټر شبکو ډیزاین، پلي کولو، او مدیریت ته اشاره کوي ترڅو د معلوماتو اړیکې یقیني کړي. دا د شبکې هارډویر، پروتوکولونه، امنیت، او د ستونزو حل شاملوي ترڅو خوندي او اغیزمن اتصال تضمین کړي.",
    se_information: "د سافټویر انجنیرۍ د سافټویر غوښتنلیکونو د ډیزاین، پراختیا، ازموینې، او ساتنې پروسه ده چې د انجنیرۍ اصولو پراساس ترسره کیږي. دا د باوري، پراخېدونکي، او مؤثره سافټویر حلونو رامینځته کولو تمرکز لري ترڅو د کاروونکو او سوداګریزو اړتیاوو پوره کولو کې مرسته وکړي.",
    is_information: "د معلوماتي سیستمونه د معلوماتو راټولولو، پروسس کولو، ذخیره کولو، او ویشلو تمرکز لري چې د ټیکنالوژۍ له لارې ترسره کیږي. دا د سافټویر، هارډویر، او معلوماتو مدیریت سره یوځای کیږي ترڅو د تصمیم نیولو او سوداګریزو عملیاتو ملاتړ وکړي.",
    neco_economics: "ملي اقتصاد د یو هېواد ټولیز اقتصادي جوړښت مطالعه کوي، چې پکې تولید، مصرف، سوداګري، او دولتي پالیسۍ شاملې دي. دا د اقتصادي وده، انفلاسیون، استخدام، او مالي مدیریت تمرکز لري ترڅو د ملي ثبات او پرمختګ یقیني کړي.",
    beco_economics: "بانکداري د مالي معاملو مدیریت ته اشاره کوي، چې پکې سپما، پورونه، پانګونه، او د تادیاتو پروسس شامل دي. دا د مالي خدماتو په برابرولو سره د افرادو، سوداګریو، او حکومتونو لپاره د اقتصادي ودې مهم رول لوبوي.",
    baeco_economics: "د سوداګرۍ اداره د سوداګریزو عملیاتو د پلان جوړولو، تنظیم، او مدیریت پروسه ده ترڅو موثریت او وده ترلاسه کړي. دا د مالي چارو، بازار موندنې، بشري سرچینو، او ستراتیژیکو پرېکړو برخې پوښي ترڅو د سوداګرۍ بریا یقیني کړي.",



  }
});



export default languages;